### PR TITLE
Add support for searching for multiple fields

### PR DESCRIPTION
**Pull request by RKrahl**
icatproject/icat.server#246 adds support for queries searching for multiple fields.  This PR adds client side support for this in python-icat. It adds special handling of the case that the ICAT `search()` API method returns a `fieldSet`.

This is just the minimal implementation and not yet final.  Still todo:
- [x] add support for corresponding JPQL queries in the `Query` class, ref. #76.
- [x] ~~improve error handling for old `icat.server` versions not supporting this.~~
- [x] add more tests.
- [x] wait for `icat.server` to be released with support for the feature.
- [ ] test with the full matrix of Python and ICAT versions.
- [x] update documentation.

### CODE REVIEW

**Comment by RKrahl** [comment]
I now investigated the behavior of the current release version 4.10.0 a little more in detail:
```python
>>> client.apiversion
StrictVersion ('4.10')
>>> client.search("SELECT o.name, o.title, o.startDate FROM Investigation o")
ERROR:suds.client:<suds.sax.document.Document object at 0x7ffade86cac8>
Traceback (most recent call last):
  ...
xml.parsers.expat.ExpatError: no element found: line 4, column 177

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
xml.sax._exceptions.SAXParseException: <unknown>:4:177: no element found
```

The SOAP response appears to be mutilated and looks like:
```xml
<?xml version=\'1.0\' encoding=\'UTF-8\'?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
  <S:Body>
    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
      <SOAP-ENV:Header/>
      <SOAP-ENV:Body>
	<SOAP-ENV:Fault>
	  <faultcode xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">env:Server</faultcode>
	  <faultstring>invocation error on ejb endpoint ICAT at /ICATService/ICAT : javax.xml.bind.MarshalException\n - with linked exception:\n[com.sun.istack.SAXException2: class [Ljava.lang.Object; nor any of its super class is known to this context.\njavax.xml.bind.JAXBException: class [Ljava.lang.Object; nor any of its super class is known to this context.].</faultstring>
	</SOAP-ENV:Fault>
      </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
```
Note that `<S:Body>` is not closed.

I don't believe it makes sense trying to catch that error condition and translate it to something meaningful. There is not much that the client side could do here to improve error handling. This item will remain a "won't fix", I'm afraid.

**Comment by RKrahl** [comment]
Note: as of the current state, this PR introduces an incompatible change in the `Query` class.

The current mainstream version of [class `Query`](https://python-icat.readthedocs.io/en/latest/query.html) allows to specify one single attribute that the search shall return for each entity object in the result. This can be set using the corresponding keyword argument `attribute` of the constructor or the method `setAttribute()`. Internally this is stored in an attribute of the `Query` object named `attribute`.

The purpose of this PR is to extent this to a list of attributes rather then a single one. Accordingly, the value changes from a single string to a list of strings. As a convenience, the constructor and the method will still accept  a single string as value, which will be taken as a shortcut of a list having one single item. But for the sake of consistency, the name of keyword argument, the internal attribute, and the method are changed to `attributes` and `setAttributes()` (in the plural) correspondingly.

**Comment by RKrahl** [comment]
The test suite including the tests searching for multiple fields runs successfully with an `icat.server` built from the current master branch.

**Comment by louise-davies** [comment]
@RKrahl just following up - are you waiting on anything from `icat.server` right now for this issue?

**Comment by RKrahl** [comment]
The only thing I was waiting for is the release of `icat.server`. As discussed in the last meeting, I plan to make an extra release 0.18.0 for this feature, so I'll have to rebase this branch and change the target branch of the PR accordingly.

**Comment by RKrahl** [comment]
I now rebased and changed the target branch as announced yesterday.

**Pull request merged**
