### PR TITLE
Get/set query conditions via string input

### LINKED ISSUE #93: Add OR Functionality to Conditions
As I'm sure you're aware, the ExPANDS search API requires the `and` and `or` keywords to be supported for the [API's WHERE query filter](https://github.com/panosc-eu/search-api/blob/master/doc/query.md#joining-queries). Python ICAT supports AND already, but does not support OR. For our implementation of the search API, we would need this functionality to be added to Python ICAT.

I'm just opening this issue for awareness :)

### PR DESCRIPTION
**Pull request by MRichards99**
Here are some proposed changes I'd like to make to Python ICAT which we help us implement the search API.

I have moved the building of the WHERE clause from `__str__()` to its own function (`get_conditions_as_str()`) so it can be more easily exposed to the search API. I've also moved some code into `get_joinattrs()` as this is used in a couple of places. This is just coding moving to their own functions so we can access more easily, there is no additional functionality in this part of the changes.

The additional functionality is `str_conditions`. This will allow us to pass in a string of conditions ready to be used in `__str__()`. You can see a demonstration of this in the test I've added. This functionality means we can build the WHERE clause ourselves and use `Query()` for the rest of the query building. We will be able to build complex WHERE clauses and use `OR`, so this PR will close #93.

I'll leave this as a draft pull request while we're still working out how to implement certain aspects of the search API (e.g. convert a request filter input in the PaNOSC data model to the ICAT schema) but it would be good if you could take a look and give us your thoughts on these changes :)

### CODE REVIEW

**Comment by RKrahl** [comment]
Hi @MRichards99, sorry for not commenting on this, but I'm rather bust with other stuff at the moment.  I'm afraid, I won't have the time to look into this until next year.

**Comment by MRichards99** [comment]
@RKrahl not a problem, I have made some changes to this pull request as I have been working on implementing the WHERE filter for the search API. My newest changes can be summarised in the following points:

- I have moved `_cond_value()` away from `addConditions()` into its own function. This may not be the most ideal, but I call this function from within the search API. The alternative would be to write my own version of this function inside the search API but I think that's a worse practice as I will need to keep the function updated when it is changed in Python ICAT
- I have changed/renamed `get_conditions_as_str()` to `search_conditions()`, with the purpose of the function changing slightly. Instead of returning all the conditions contained within the query, I search for a specific condition that matches the field name, operator and value. This means I can get the correct JPQL syntax and append it to a list of JPQL conditions within the search API. This is part of the logic on the search API to build its own WHERE clauses for queries which have AND/OR boolean operator. I have added a test to test the logic of `search_conditions()`
- I did call `get_conditions_as_str()` from within `Query()` as the contents of that function was existing code which I had moved from `__str__()`. Since I have modified the code, the code which constructs WHERE clauses in `__str__()` is now the same as before I made any changes

In the new year, I will implement the include filter to the search API. I do not expect to make further changes to Python ICAT for this so I will make this pull request ready for review.

**Comment by MRichards99** [comment]
@RKrahl is there any progress on this? I've implemented the include filter on the search API and haven't needed to make any further changes to Python ICAT/this branch so this is ready for review

**Comment by RKrahl** [comment]
@MRichards99, sorry, I won't be able to look into it this week.

**Comment by RKrahl** [comment]
I'm not sure it I'm happy with the direction this PR takes.  Consider the following example, it is derived from a [tutorial example](https://python-icat.readthedocs.io/en/0.20.1/tutorial-search.html):
```python
>>> query_0 = Query(client, "Investigation", conditions={"name": "= '12100409-ST'"})
>>> str(query_0)
"SELECT o FROM Investigation o WHERE o.name = '12100409-ST'"
>>> query_0.addConditions({"visitId": "= '1.1-P'"})
>>> str(query_0)
"SELECT o FROM Investigation o WHERE o.name = '12100409-ST' AND o.visitId = '1.1-P'"
>>> query_1 = Query(client, "Investigation", str_conditions="o.name = '12100409-ST'")
>>> str(query_1)
"SELECT o FROM Investigation o WHERE o.name = '12100409-ST'"
>>> query_1.addConditions({"visitId": "= '1.1-P'"})
>>> str(query_1)
"SELECT o FROM Investigation o WHERE o.name = '12100409-ST'"
```

Although `query_0` and `query_1` look the same (`"SELECT o FROM Investigation o WHERE o.name = '12100409-ST'"`) after creating them, I can incrementally add a conditions to `query_0`, but not to `query_1`.  Even worse, the call to add a condition to `query_1` seem to succeed, but it is silently ignored.

Note that the ability to incrementally build queries is a fundamental feature in the `Query` class.  This was actually the reason why I created this class in the first place, because it's so awkward when you try to do it with string manipulation.

**Comment by RKrahl** [comment]
Note that I do understand why you want that feature to be able to override the conditions with a plain string. I assume it's related to #93: the abilities of the query builder are too limited for your use case. Unfortunately, I believe it's very difficult to add that feature in a way that would be consistent with the design of `class Query` as a general purpose library class. I already suggested in the discussion in #93 to create a dedicated query translator for the search API rather than using `Query`.

I'd like to make a proposal: 

I'm happy to add read only properties to `Query` to access the components of the query.  E.g. something like:
```python
>>> query = Query(client, "Datafile", conditions={"dataset.name": "= 'e208945'", "dataset.investigation.name": "= '12100409-ST'"}, order=[("name", "ASC")], limit=(0,3))
>>> str(query)
"SELECT o FROM Datafile o JOIN o.dataset AS ds JOIN ds.investigation AS i WHERE i.name = '12100409-ST' AND ds.name = 'e208945' ORDER BY o.name ASC LIMIT 0, 3"
>>> query.select_clause
'SELECT o FROM Datafile o'
>>> query.join_clause
'JOIN o.dataset AS ds JOIN ds.investigation AS i'
>>> query.where_clause
"WHERE i.name = '12100409-ST' AND ds.name = 'e208945'"
>>> query.order_clause
'ORDER BY o.name ASC'
>>> query.include_clause
>>> query.limit_clause
'LIMIT 0, 3'
```
These properties would also be used internally to compile the query string.

Based on that, you could easily derive a class for your own purpose that enables overriding the condition.  Something like:
```python
from icat.query import Query

class ConditionSettingQuery(Query):

    def __init__(self, client, entity,
                 attributes=None, aggregate=None, order=None,
                 conditions=None, includes=None, limit=None,
                 join_specs=None, str_conditions=None):

        super().__init__(client, entity,
                 attributes=attributes, aggregate= aggregate, order=order,
                 conditions=conditions, includes=includes, limit=limit,
                 join_specs=join_specs)
        self.setConditionsByString(str_conditions)

    def setConditionsByString(self, str_conditions):
        self._str_conditions = str_conditions

    @property
    def where_clause(self):
        if self._str_conditions:
            return self._str_conditions
        else:
            return super().where_clause
```
(I believe that would already be the complete implementation.)

Of course, that `class ConditionSettingQuery` would suffer from the same inconsistency that I described in my last comment.  But for a dedicated class, developed for a special use case, the requirements for consistency is much lower than for a library class.

**Pull request closed without merging**
